### ISSUE TITLE
Я что-то не то ввёл и ничего не поломалось, хотя должно было

### ISSUE THREAD

**Issue by KonstantinFed** [Eraphion/NewCoolProject#1]
Программа не отслеживает введение отрицательных значений вместимости для дисков и отдельных композиций. Это может нарушить логику приложения. Прошу исправить данное недоразумение путём сложных логических операций.
![image](https://cloud.githubusercontent.com/assets/23392551/26542861/b9317f6a-4485-11e7-9a1a-6a2e769216e3.png)

**Comment by KonstantinFed** [comment]
Ещё один скриншот, демонстрирующий, что я говорю чистую правду
![image](https://cloud.githubusercontent.com/assets/23392551/26542922/00c6ca1a-4486-11e7-91f4-6a3e20eae4e9.png)

**Comment by Eraphion** [comment]
Наша команда разработчиков искренне благодарит Вас за сообщение о найденной ошибке. Без Вас мы бы нашли её гораздо позже. Мы обсудили возможные варианты решения возникшей проблемы и решили её. В последнее версии Вы лично можете убедиться, что проблема полностью искоренена. Где бы Вы ни были, спасибо за обращение!
![image](https://cloud.githubusercontent.com/assets/23791960/26543398/12fe4cce-4488-11e7-9b7f-033beef009c0.png)

**Comment by KonstantinFed** [comment]
Все решено, я очень рад, теперь я буду использовать только Вашу программу, так как аналогов в принципе нет. Спасибо за столь быстрый отзыв
Костя
